POST http://localhost:3333/eventos
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/afb72bc7-535a-43f2-aecd-59deb621f229/attendees
Content-Type: application/json

{
    "name": "teste",
    "email": "guilhermedev200@hotmail.com"
}

###

GET http://localhost:3333/events/afb72bc7-535a-43f2-aecd-59deb621f229

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/afb72bc7-535a-43f2-aecd-59deb621f229/attendees?query=teste